### ISSUE TITLE
In step 4, run/open Teensyduino IDE, not Arduino IDE?

### ISSUE THREAD

**Issue by mdotslash** [BleepLabs/Dadageek-August20#1]
I didn't see the boards / ports in the standard Arduino IDE (not sure if that's my OS, MBP 10.11.6).  I did see them in the Teensyduino IDE though.

**Comment by BleepLabs** [comment]
Follow the guide here to install Teensyduio:
https://github.com/BleepLabs/Arduino-Light-And-Sound/wiki/Arduino-software-first-steps
Sorry I sent you the old link the first time.
